name: Niskala Airaha
avatar: images/profile.webp # Avatar image. Default to "images/profile.webp".
bio: 'Sang Wibu Siluman'
#company: Entah # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
location: Tanah Melayu # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
   layout: compact
}
social:
  email: niskala5570@gmail.com
  github: niskala5570
  twitter: niskala5570
  # patreon: razonyang
  # paypal: razonyang
  rss: "" # Remove RSS
