ms:
  languageName: Melayu
  weight: 1
  params:
    dateFormat: '2006-01-02'
    description: 一个快速、响应式和功能丰富的 Hugo 博客主题
    keywords: 'Hugo, Bootstrap, 博客主题'
    archive:
      dateFormat: 01-02

ms-Arab:
  languageName: ملايو
  languageDirection: rtl
  weight: 2

en:
  languageName: English
  weight: 3


